# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/fragment-alpha-sdk/all/fragment-alpha-sdk.rbi
#
# fragment-alpha-sdk-0.1.10

module FragmentGraphQl
  extend T::Sig
end
class FragmentGraphQl::CustomHTTP < GraphQL::Client::HTTP
  def headers(*args, **, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class InvalidName___Module_0x00___UnresolvedTypeError_7 < GraphQL::UnresolvedTypeError
end
class InvalidName___Class_0x00___UnresolvedValueError_8 < GraphQL::Schema::Enum::UnresolvedValueError
end
class InvalidName___Class_0x00___UnresolvedValueError_9 < GraphQL::Schema::Enum::UnresolvedValueError
end
class InvalidName___Class_0x00___UnresolvedValueError_10 < GraphQL::Schema::Enum::UnresolvedValueError
end
class InvalidName___Class_0x00___UnresolvedTypeError_11 < GraphQL::UnresolvedTypeError
end
class InvalidName___Class_0x00___UnresolvedTypeError_12 < GraphQL::UnresolvedTypeError
end
class InvalidName___Class_0x00___UnresolvedValueError_13 < GraphQL::Schema::Enum::UnresolvedValueError
end
class InvalidName___Class_0x00___UnresolvedTypeError_14 < GraphQL::UnresolvedTypeError
end
class InvalidName___Class_0x00___UnresolvedTypeError_15 < GraphQL::UnresolvedTypeError
end
class InvalidName___Class_0x00___UnresolvedTypeError_16 < GraphQL::UnresolvedTypeError
end
class InvalidName___Class_0x00___UnresolvedValueError_17 < GraphQL::Schema::Enum::UnresolvedValueError
end
class InvalidName___Class_0x00___UnresolvedValueError_18 < GraphQL::Schema::Enum::UnresolvedValueError
end
class InvalidName___Class_0x00___UnresolvedValueError_19 < GraphQL::Schema::Enum::UnresolvedValueError
end
class InvalidName___Class_0x00___UnresolvedValueError_20 < GraphQL::Schema::Enum::UnresolvedValueError
end
class InvalidName___Class_0x00___UnresolvedValueError_21 < GraphQL::Schema::Enum::UnresolvedValueError
end
class InvalidName___Class_0x00___UnresolvedValueError_22 < GraphQL::Schema::Enum::UnresolvedValueError
end
class InvalidName___Class_0x00___UnresolvedTypeError_23 < GraphQL::UnresolvedTypeError
end
class InvalidName___Class_0x00___UnresolvedTypeError_24 < GraphQL::UnresolvedTypeError
end
class InvalidName___Class_0x00___UnresolvedTypeError_25 < GraphQL::UnresolvedTypeError
end
class InvalidName___Class_0x00___UnresolvedValueError_26 < GraphQL::Schema::Enum::UnresolvedValueError
end
class InvalidName___Module_0x00___UnresolvedTypeError_27 < GraphQL::UnresolvedTypeError
end
class InvalidName___Class_0x00___UnresolvedValueError_28 < GraphQL::Schema::Enum::UnresolvedValueError
end
class InvalidName___Class_0x00___UnresolvedTypeError_29 < GraphQL::UnresolvedTypeError
end
class InvalidName___Class_0x00___UnresolvedTypeError_30 < GraphQL::UnresolvedTypeError
end
class InvalidName___Class_0x00___UnresolvedTypeError_31 < GraphQL::UnresolvedTypeError
end
class InvalidName___Class_0x00___UnresolvedTypeError_32 < GraphQL::UnresolvedTypeError
end
class InvalidName___Class_0x00___UnresolvedValueError_33 < GraphQL::Schema::Enum::UnresolvedValueError
end
class InvalidName___Class_0x00___UnresolvedTypeError_34 < GraphQL::UnresolvedTypeError
end
class InvalidName___Class_0x00___UnresolvedValueError_35 < GraphQL::Schema::Enum::UnresolvedValueError
end
class FragmentGraphQl::Schema < GraphQL::Schema
  def self.resolve_type(type, obj, ctx); end
  extend GraphQL::Schema::SubclassGetReferencesTo
end
class InvalidName___Class_0x00___UnresolvedValueError_36 < GraphQL::Schema::Enum::UnresolvedValueError
end
class InvalidName___Class_0x00___UnresolvedValueError_37 < GraphQL::Schema::Enum::UnresolvedValueError
end
class InvalidName___Class_0x00___UnresolvedValueError_38 < GraphQL::Schema::Enum::UnresolvedValueError
end
class InvalidName___Class_0x00___UnresolvedValueError_39 < GraphQL::Schema::Enum::UnresolvedValueError
end
class InvalidName___Module_0x00___Query_40 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___CustomCurrenciesConnection_41 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___Currency_42 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
module InvalidName___Module_0x00___CurrencyCode_43
end
class InvalidName___Module_0x00___PageInfo_44 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___Ledger_45 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
module InvalidName___Module_0x00___LedgerTypes_46
end
class InvalidName___Module_0x00___Schema_47 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___LedgersConnection_48 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___SchemaVersion_49 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___LedgerMigrationConnection_50 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___LedgerMigration_51 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
module InvalidName___Module_0x00___LedgerMigrationStatus_52
end
class InvalidName___Module_0x00___SchemaVersionConnection_53 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___LedgerAccountsConnection_54 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___LedgerAccount_55 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
module InvalidName___Module_0x00___LedgerAccountTypes_56
end
class InvalidName___Module_0x00___LedgerAccountConsistencyConfig_57 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
module InvalidName___Module_0x00___BalanceUpdateConsistencyMode_58
end
module InvalidName___Module_0x00___LedgerLinesConsistencyMode_59
end
class InvalidName___Module_0x00___CurrencyAmountConnection_60 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___CurrencyAmount_61 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
module InvalidName___Module_0x00___Link_62
end
class InvalidName___Module_0x00___ExternalAccount_63 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
module InvalidName___Module_0x00___CurrencyMode_64
end
class InvalidName___Module_0x00___TxsConnection_65 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___Tx_66 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___LedgerLinesConnection_67 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___LedgerLine_68 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
module InvalidName___Module_0x00___TxType_69
end
module InvalidName___Module_0x00___ExternalTransferType_70
end
class InvalidName___Module_0x00___LedgerEntry_71 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___LedgerEntryCondition_72 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___LedgerAccountCondition_73 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___Int96Condition_74 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___LedgerEntryTag_75 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___LedgerEntryGroup_76 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___LedgerEntriesConnection_77 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___LedgerEntryGroupBalanceConnection_78 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___LedgerEntryGroupBalance_79 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___LedgerEntryGroupsConnection_80 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___LinksConnection_81 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___SchemaConnection_82 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
class InvalidName___Module_0x00___Mutation_83 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
module InvalidName___Module_0x00___CreateLedgerResponse_84
end
class InvalidName___Module_0x00___CreateLedgerResult_85 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___CreateLedgerResponse_84
end
class InvalidName___Module_0x00___BadRequestError_86 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___AddLedgerEntryResponse_93
  include InvalidName___Module_0x00___CreateCustomCurrencyResponse_94
  include InvalidName___Module_0x00___CreateCustomLinkResponse_95
  include InvalidName___Module_0x00___CreateLedgerAccountResponse_89
  include InvalidName___Module_0x00___CreateLedgerAccountsResponse_91
  include InvalidName___Module_0x00___CreateLedgerResponse_84
  include InvalidName___Module_0x00___Error_87
  include InvalidName___Module_0x00___LinkResponse_99
  include InvalidName___Module_0x00___ReconcileTxResponse_92
  include InvalidName___Module_0x00___StoreSchemaResponse_98
  include InvalidName___Module_0x00___SyncCustomAccountsResponse_96
  include InvalidName___Module_0x00___SyncCustomTxsResponse_97
  include InvalidName___Module_0x00___UpdateLedgerAccountResponse_90
  include InvalidName___Module_0x00___UpdateLedgerResponse_88
end
module InvalidName___Module_0x00___Error_87
end
class InvalidName___Module_0x00___InternalError_100 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___AddLedgerEntryResponse_93
  include InvalidName___Module_0x00___CreateCustomCurrencyResponse_94
  include InvalidName___Module_0x00___CreateCustomLinkResponse_95
  include InvalidName___Module_0x00___CreateLedgerAccountResponse_89
  include InvalidName___Module_0x00___CreateLedgerAccountsResponse_91
  include InvalidName___Module_0x00___CreateLedgerResponse_84
  include InvalidName___Module_0x00___Error_87
  include InvalidName___Module_0x00___LinkResponse_99
  include InvalidName___Module_0x00___ReconcileTxResponse_92
  include InvalidName___Module_0x00___StoreSchemaResponse_98
  include InvalidName___Module_0x00___SyncCustomAccountsResponse_96
  include InvalidName___Module_0x00___SyncCustomTxsResponse_97
  include InvalidName___Module_0x00___UpdateLedgerAccountResponse_90
  include InvalidName___Module_0x00___UpdateLedgerResponse_88
end
module InvalidName___Module_0x00___UpdateLedgerResponse_88
end
class InvalidName___Module_0x00___UpdateLedgerResult_101 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___UpdateLedgerResponse_88
end
module InvalidName___Module_0x00___CreateLedgerAccountResponse_89
end
class InvalidName___Module_0x00___CreateLedgerAccountResult_102 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___CreateLedgerAccountResponse_89
end
module InvalidName___Module_0x00___UpdateLedgerAccountResponse_90
end
class InvalidName___Module_0x00___UpdateLedgerAccountResult_103 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___UpdateLedgerAccountResponse_90
end
module InvalidName___Module_0x00___CreateLedgerAccountsResponse_91
end
class InvalidName___Module_0x00___CreateLedgerAccountsResult_104 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___CreateLedgerAccountsResponse_91
end
class InvalidName___Module_0x00___IkReplay_105 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
module InvalidName___Module_0x00___ReconcileTxResponse_92
end
class InvalidName___Module_0x00___ReconcileTxResult_106 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___ReconcileTxResponse_92
end
module InvalidName___Module_0x00___AddLedgerEntryResponse_93
end
class InvalidName___Module_0x00___AddLedgerEntryResult_107 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___AddLedgerEntryResponse_93
end
module InvalidName___Module_0x00___CreateCustomCurrencyResponse_94
end
class InvalidName___Module_0x00___CreateCustomCurrencyResult_108 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___CreateCustomCurrencyResponse_94
end
module InvalidName___Module_0x00___CreateCustomLinkResponse_95
end
class InvalidName___Module_0x00___CreateCustomLinkResult_109 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___CreateCustomLinkResponse_95
end
module InvalidName___Module_0x00___SyncCustomAccountsResponse_96
end
class InvalidName___Module_0x00___SyncCustomAccountsResult_110 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___SyncCustomAccountsResponse_96
end
module InvalidName___Module_0x00___SyncCustomTxsResponse_97
end
class InvalidName___Module_0x00___SyncCustomTxsResult_111 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___SyncCustomTxsResponse_97
end
module InvalidName___Module_0x00___StoreSchemaResponse_98
end
class InvalidName___Module_0x00___StoreSchemaResult_112 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___StoreSchemaResponse_98
end
class InvalidName___Module_0x00___NotFoundError_113 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___Error_87
  include InvalidName___Module_0x00___LinkResponse_99
end
module InvalidName___Module_0x00___ReadBalanceConsistencyMode_114
end
module InvalidName___Module_0x00___ExternalTxSource_115
end
class InvalidName___Module_0x00___ExternalAccountsConnection_116 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
end
module InvalidName___Module_0x00___IncreaseEnv_117
end
class InvalidName___Module_0x00___IncreaseLink_118 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___LinkResponse_99
  include InvalidName___Module_0x00___Link_62
end
module InvalidName___Module_0x00___UnitEnv_119
end
class InvalidName___Module_0x00___UnitLink_120 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___Link_62
end
class InvalidName___Module_0x00___CustomLink_121 < GraphQL::Client::Schema::ObjectClass
  def self.fields; end
  def self.type; end
  extend GraphQL::Client::Schema::BaseType
  extend GraphQL::Client::Schema::ObjectType
  include InvalidName___Module_0x00___LinkResponse_99
  include InvalidName___Module_0x00___Link_62
end
module InvalidName___Module_0x00___LinkResponse_99
end
module InvalidName___Module_0x00___SchemaConsistencyMode_122
end
module FragmentGraphQl::Queries::StoreSchema
end
module FragmentGraphQl::Queries::CreateLedger
end
module FragmentGraphQl::Queries::CreateLedgerAccounts
end
module FragmentGraphQl::Queries::ReconcileTx
end
module FragmentGraphQl::Queries::AddLedgerEntry
end
module FragmentGraphQl::Queries::UpdateLedger
end
module FragmentGraphQl::Queries::UpdateLedgerAccount
end
module FragmentGraphQl::Queries::NewCustomLink
end
module FragmentGraphQl::Queries::SyncBankAccounts
end
module FragmentGraphQl::Queries::LedgerEntry
end
module FragmentGraphQl::Queries::Ledger
end
module FragmentGraphQl::Queries::GetLedgerAccounts
end
module FragmentGraphQl::Queries::GetAccountLinesOnDate
end
module FragmentGraphQl::Queries::GetLedgerEntries
end
module FragmentGraphQl::Queries::GetLinkedLedgerAccounts
end
module FragmentGraphQl::Queries::GetBalances
end
module FragmentGraphQl::Queries
end
class FragmentClient
  def create_conn(*args, **, &blk); end
  def define_method_from_queries(queries); end
  def get_token(*args, **, &blk); end
  def initialize(*args, **, &blk); end
  def query(*args, **, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
