name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.3', '3.2', '3.1']

    steps:
        - uses: actions/checkout@v2
    
        - name: Setup Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: ${{ matrix.ruby }}
    
        - name: Bundle install
          run: |
            gem install bundler
            bundle install --jobs 4 --retry 3
    
        - name: Run tests
          run: bundle exec rake test

        - name: Verify schema is up-to-date
          run: |
            bundle exec rake graphql:update_schema
            git diff --exit-code
            exit $?

        - name: Validate GraphQL queries
          run: |
            export EXITCODE=$(grep -E '^(mutation|query) [a-z]' lib/queries.graphql || echo $?)
            if [[ $EXITCODE -eq 0 ]]; then
              echo "Failed to validate GraphQL queries."
              echo "Ensure that GraphQL named queries are in title-case."
              exit 1
            fi
