on:
  workflow_dispatch:

name: Update SDK queries
jobs:
  updateQueries:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1
        id: generate-token
        with:
          app_id: ${{ secrets.PR_APP_ID }}
          private_key: ${{ secrets.PR_APP_PRIVATE_KEY }}

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          path: graphql-queries
          repository: fragment-dev/graphql-queries
          token: ${{ steps.generate-token.outputs.token }}

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        name: Checkout fragment-ruby
        with:
          path: fragment-ruby

      - name: Use Ruby
        uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v1
        with:
          ruby-version: '3.3.6'

      - name: Install dependencies
        working-directory: ./fragment-ruby
        run: |
          bundle install

      - name: Copy queries.graphql
        working-directory: ./fragment-ruby
        run: |
          cp ../graphql-queries/queries.graphql lib/queries.graphql
          sed -i -e 's/^query \([a-z]\)/query \U\1/g;s/^mutation \([a-z]\)/mutation \U\1/g' lib/queries.graphql

      - name: Generate SDK
        working-directory: ./fragment-ruby
        run: |
          bundle exec rake graphql:update_schema

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          path: ./fragment-ruby
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: 'Update Ruby SDK queries'
          title: 'Update Ruby SDK queries'
          base: 'dev'
          branch: update-sdk-queries/${{ github.run_id }}
          body: >
            This PR is auto-generated by github action.
